### ISSUE TITLE
Can we have some kinds of TODO list here?

### ISSUE THREAD

**Issue by MassD** [eatonphil/owebl#11]
So it will be easier to contribute.

**Comment by eatonphil** [comment]
Glad to see some interest!

Well, have you played around with it? What would you like to see? Some notes I have with my guess at relative (difficulty, length of time) out of longest, 5:
- Forking is not completely scalable (5, 5)
- SSL termination (5, 5)
  - This would be awesome and so much fun but pretty redundant
- Missing a standard template library (2, 5)
- Support for sending media (2, 2)
- But I think most importantly, it is missing recipes in the cookbook for:
  - database integration (3, 3.5)
  - session management (3, 3.5)
  - encryption (3, 3.5)
  - a simple blog? (2, 3)

It would also definitely be nice to have a CMS available if only for demonstration of techniques.

**Comment by eatonphil** [comment]
Also, sorry for the late response and the general lack of effort on owebl. I just started a new job.

**Comment by eatonphil** [comment]
There is now a TODO.md
