### ISSUE TITLE
Consider an OPAM package ?

### ISSUE THREAD

**Issue by AltGr** [eatonphil/owebl#9]
It should now be quite straight-forward, see https://opam.ocaml.org/doc/Packaging.html

**Comment by eatonphil** [comment]
Sorry for the late response, yes that is a step I'm thinking about. Currently my priority is to make it as easy to get started as possible. To be honest, I can't make heads or tails of that Packaging documentation. So for now, this will be not be possible until I figure it out for myself.

**Comment by AltGr** [comment]
Sorry to hear that, I'd be glad to improve the documentation if you can give some pointers of where it failed to be helpful !

**Comment by eatonphil** [comment]
If you have the time to help me out, the major issue is just successfully compiling into a library. I have a stackoverflow question [here](http://stackoverflow.com/questions/29178010/ocamlfind-local-library-unbound-module). Once this is out of the way, I think submitting the opam package should be pretty easy!

**Comment by eatonphil** [comment]
https://opam.ocaml.org/packages/owebl/owebl.0.1/
